language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
    - php: hhvm-nightly

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

before_script:
  - composer selfupdate
  - composer install

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: false